# Generated by Django 4.2.6 on 2023-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=10000)),
                ('index', models.IntegerField()),
                ('block_data', models.TextField()),
                ('block_hash', models.CharField(max_length=100)),
                ('proof_of_work', models.CharField(max_length=100)),
                ('previous_block_hash', models.CharField(max_length=100)),
                ('transaction', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'block',
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=20)),
                ('node_ID', models.CharField(max_length=40)),
                ('blockchain_copy', models.JSONField(blank=True, null=True)),
                ('Email', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('private_key', models.CharField(max_length=100)),
                ('amount', models.IntegerField(max_length=10000)),
                ('block_hashes', models.JSONField(blank=True, null=True)),
                ('file_name', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Zero_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_blocks', models.IntegerField()),
                ('index', models.IntegerField()),
                ('proof', models.IntegerField()),
            ],
            options={
                'db_table': 'Info',
            },
        ),
    ]
