# Generated by Django 4.2.6 on 2023-12-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blockchain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zero_block',
        ),
    ]
